### ISSUE TITLE
I get compilation error "unnecessary parentheses around function argument"

### ISSUE THREAD

**Issue by antonjan** [cubehub/doppler#7]
Hi Could please help

I am compiling on Ubuntu 16.04

sudo cargo build --release
   Compiling doppler v1.1.9 (file:///home/anton/Downloads/doppler)
warning: unnecessary parentheses around function argument
  --> src/main.rs:91:88
   |
91 |                 let slice = unsafe {slice::from_raw_parts(output.as_ptr() as *const _, (output.len() * 8))};
   |                                                                                        ^^^^^^^^^^^^^^^^^^ help: remove these parentheses
   |
   = note: #[warn(unused_parens)] on by default

    Finished release [optimized] target(s) in 1.42 secs

**Comment by andresv** [comment]
It is just a warning. Actually it built.
