### ISSUE TITLE
Compile error in rust

### ISSUE THREAD

**Issue by doctorvenables** [cubehub/doppler#8]
Hi,
At the step '   Compiling rustc-serialize v0.3.18'
There is an error:
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.18/src/serialize.rs:145:45
    |
145 |                                             &f_name: &str,
    |                                             ^^^^^^^

With a bit of research, it turns out that if you update rustc-serialize with this line:
cargo update -p rustc-serialize

And then run the compile instruction, the error goes away and everything compiles fine.
Mark

**Comment by andresv** [comment]
Fixed.
